on:
  create:

jobs:
  bundle:
    name: Bundle release
    runs-on: ubuntu-latest
    if: github.event.release.target_commitish == 'main'
    steps:
    - name: Checkout Source
      uses: actions/checkout@v2
    - name: Code Build
      id: build
      run: |
        npm install
        npm run test
        npm run build
    - name: Compress
      run: |
        zip -r bundle-${{ github.event.release.tag_name }}.zip dist
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: bundle-${{ github.event.release.tag_name }}
        path: bundle-${{ github.event.release.tag_name }}.zip
        retention-days: 7
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.event.release.target_commitish == 'main'
    needs: bundle
    steps:
    - name: Checkout Source
      uses: actions/checkout@v2
    - name: Download bundle
      uses: actions/download-artifact@v2
      with:
        name: bundle-${{ github.event.release.tag_name }}
    - name: Unzip bundle
      run: |
        unzip bundle-${{ github.event.release.tag_name }}.zip
    - name: Deploy via CDK
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      run: |
        npm install --only dev
        npm run cdk deploy -- --require-approval never
